### ISSUE TITLE
Exclude Snippets that Don't Match Regex:

### ISSUE THREAD

**Issue by zanderbush** [sinerasis/Greed#1]
Do you know how to exclude snippets that don't match a regex? Say, I wanted to return a capital "Opportunity cost." It would exclude all snippets that contained "opportunity cost."

**Comment by sinerasis** [comment]
I'm not sure I understand. The Greed extension doesn't do any regex matching so I'm not sure how this is relevant.

If you want to match a specific string using regex, you're probably going to need to do something like (^opportunity cost.). The string contained within the parenthesis is case sensitive.
